version: 2.1

executors:
  android:
    docker:
      - image: cimg/android:2021.08.1
    working_directory: ~/top/example
    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:MaxPermSize=256m -XX:+HeapDumpOnOutOfMemoryError" -Dorg.gradle.daemon=false'
  plugin:
    docker:
      - image: circleci/openjdk:8
    working_directory: ~/top
    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:MaxPermSize=256m -XX:+HeapDumpOnOutOfMemoryError" -Dorg.gradle.daemon=false'

commands:
  setup_workspace:
    steps:
      - checkout:
          path: ~/top

  restore_gradle_cache:
    parameters: &gradle_cache_parameters
      cache_version:
        type: string
        default: v3
      cache_name:
        type: string
    steps:
      - run: ~/top/.circleci/generate_hashfile > ~/<< parameters.cache_name >>.lock
      - restore_cache:
          keys:
            - gradle-<< parameters.cache_version >>-{{ checksum "~/<< parameters.cache_name >>.lock" }}
  save_gradle_cache:
    parameters: *gradle_cache_parameters
    steps:
      - save_cache:
          paths:
            - ~/.android
            - ~/.gradle
            - .gradle
          key: gradle-<< parameters.cache_version >>-{{ checksum "~/<< parameters.cache_name >>.lock" }}
  switch_java:
    parameters:
      jdk-version:
        type: string
    steps:
      - run:
          name: Check the current configurations
          command: |
            java -version
            update-java-alternatives --list || true
      - run:
          name: Get the 
          command: |
            readonly distribution="$(update-java-alternatives -l | grep "java-1.<< parameters.jdk-version >>" | cut -d " " -f1)"

            if [ -z "${distribution}" ]; then
              echo "Couldn't get the jdk distribution name. Please check if the command above works." 1>&2
              exit 1
            fi

            echo "${distribution}"
            echo "export JDK_DISTRIBUTION_NAME=${distribution}" >> $BASH_ENV
      - run: sudo update-java-alternatives -s "${JDK_DISTRIBUTION_NAME}" || true
      - run: java -version
  switch_gradle:
    parameters:
      gradle-version:
        type: string
    steps:
      - run:
          name: Use the specified Gradle version
          command: gradle wrapper --gradle-version {{ parameters.gradle-version }} --distribution-type --bin

jobs:
  install_plugin_jars:
    executor: plugin
    steps:
      - setup_workspace
      - restore_gradle_cache:
          cache_name: plugin
      - run: ./gradlew publishToMavenLocal
      - persist_to_workspace:
          root: ~/.m2
          paths:
            - repository

  schema_test:
    parameters: &build_env_parameters
      jdk-version:
        type: string
        description: JDK version. 8 or 11
      gradle-version:
        type: string
        description: Gradle version. e.g. 6.0.2
    executor: android
    steps:
      - setup_workspace
      - switch_java:
          jdk-version: << parameters.jdk-version >>
      - switch_gradle:
          gradle-version: << parameters.gradle-version >>
      - restore_gradle_cache:
          cache_name: example-<< parameters.gradle-version >>
      - attach_workspace:
          at: ~/.m2
      - run: ./gradlew assembleYellowBlueRelease # it's okay if succeed

  acceptance_test:
    parameters: *build_env_parameters
    executor: android
    steps:
      - setup_workspace
      - switch_java:
          jdk-version: << parameters.jdk-version >>
      - switch_gradle:
          gradle-version: << parameters.gradle-version >>
      - restore_gradle_cache:
          cache_name: example-<< parameters.gradle-version >>
      - attach_workspace:
          at: ~/.m2
      - run: 
          name: Validate
          command: ~/top/.circleci/validation_test
      - run: 
          name: Init
          command: ~/top/.circleci/init_test
      - run:
          name: Ignore
          command: ~/top/.circleci/ignore_test
      - run: 
          name: Merge
          command: ~/top/.circleci/merge_test
      - run:
          name: Inspect
          command: ~/top/.circleci/inspection_test
      - run:
          name: Visualize
          command: ~/top/.circleci/visualization_test
      - store_artifacts:
          path: app/src/yellowBlueRelease/assets
          destination: assets
      # TODO snapshot tests provided by espresso
      - save_gradle_cache:
          cache_name: example-<< parameters.gradle-version >>

workflows:
  version: 2
  on_commit:
    jobs:
      - install_plugin_jars
      - acceptance_test:
          requires:
            - install_plugin_jars
          matrix:
            parameters:
              jdk-version: ['8', '11']
              gradle-version: ['6.0.1', '7.0.2']
      - schema_test:
          requires:
            - install_plugin_jars
          matrix:
            parameters:
              jdk-version: ['8', '11']
              gradle-version: ['6.0.1', '7.0.2']