version: 2.1

executors:
  android:
    docker:
      - image: circleci/android@sha256:e8a82728a4d2a1b7085f3ada107b492b76aeeefaa7bf739b5addace0a73ba79d
    working_directory: ~/top/example
    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:MaxPermSize=256m -XX:+HeapDumpOnOutOfMemoryError" -Dorg.gradle.daemon=false'
  plugin:
    docker:
      - image: circleci/openjdk:8
    working_directory: ~/top
    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:MaxPermSize=256m -XX:+HeapDumpOnOutOfMemoryError" -Dorg.gradle.daemon=false'

commands:
  setup_workspace:
    steps:
      - checkout:
          path: ~/top

  restore_gradle_cache:
    parameters: &gradle_cache_parameters
      cache_version:
        type: string
        default: v3
      cache_name:
        type: string
    steps:
      - run: ~/top/.circleci/generate_hashfile > ~/<< parameters.cache_name >>.lock
      - restore_cache:
          keys:
            - gradle-<< parameters.cache_version >>-{{ checksum "~/<< parameters.cache_name >>.lock" }}
  save_gradle_cache:
    parameters: *gradle_cache_parameters
    steps:
      - save_cache:
          paths:
            - ~/.android
            - ~/.gradle
            - .gradle
          key: gradle-<< parameters.cache_version >>-{{ checksum "~/<< parameters.cache_name >>.lock" }}

jobs:
  install_plugin_jars:
    executor: plugin
    steps:
      - setup_workspace
      - restore_gradle_cache:
          cache_name: plugin
      - run: ./gradlew publishToMavenLocal
      - persist_to_workspace:
          root: ~/.m2
          paths:
            - repository

  schema_test:
    executor: android
    steps:
      - setup_workspace
      - restore_gradle_cache:
          cache_name: example
      - attach_workspace:
          at: ~/.m2
      - run: ./gradlew assembleYellowBlueRelease # it's okay if succeed

  acceptance_test:
    executor: android
    steps:
      - setup_workspace
      - restore_gradle_cache:
          cache_name: example
      - attach_workspace:
          at: ~/.m2
      - run: 
          name: Validate
          command: ~/top/.circleci/validation_test
      - run: 
          name: Init
          command: ~/top/.circleci/init_test
      - run:
          name: Ignore
          command: ~/top/.circleci/ignore_test
      - run: 
          name: Merge
          command: ~/top/.circleci/merge_test
      - run:
          name: Inspect
          command: ~/top/.circleci/inspection_test
      - run:
          name: Visualize
          command: ~/top/.circleci/visualization_test
      - store_artifacts:
          path: app/src/yellowBlueRelease/assets
          destination: assets
      # TODO snapshot tests provided by espresso
      - save_gradle_cache:
          cache_name: example

workflows:
  version: 2
  on_commit:
    jobs:
      - install_plugin_jars
      - acceptance_test:
          requires:
            - install_plugin_jars
      - schema_test:
          requires:
            - install_plugin_jars